name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: krjordan/ryanjordan.dev:latest
          build-args: |
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            RESEND_FROM_EMAIL=${{ secrets.RESEND_FROM_EMAIL }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy docker-compose.prod.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.prod.yml'
          target: '~/ryanjordan.dev'

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ryanjordan.dev
            if [ -f docker-compose.prod.yml ]; then
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d
            else
              echo "docker-compose.prod.yml not found"
              exit 1
            fi
